import json
import re
import string
import uuid
from datetime import datetime, timezone
import os
from dotenv import load_dotenv
from groq import Groq

from flask import Flask, request, jsonify


app = Flask(__name__)

from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=["20 per minute"],
    storage_uri="memory://",
)

load_dotenv()

client = Groq(
    api_key=os.getenv("GROQ_API_KEY")
)

LOG_PATH = "audit_log.jsonl"

def log_event(entry):
    entry["timestamp"] = datetime.now(timezone.utc).isoformat()
    with open(LOG_PATH, "a") as f:
        f.write(json.dumps(entry) + "\n")


def get_log(limit=20):
    try:
        with open(LOG_PATH, "r") as f:
            lines = f.readlines()
    except FileNotFoundError:
        return []

    return [json.loads(line) for line in lines[-limit:]]


def llm_based_classifier(text):
    """
    First detection signal using Groq.

    Returns:
        {
            "signal": "llm_classifier",
            "ai_probability": float (0-1),
            "reasoning": str
        }
    """

    prompt = f"""
    You are an AI-content attribution assistant.

    Analyze the following text and estimate the probability that it was generated by an AI language model.
    Consider stylistic consistency, repetition, lexical diversity, sentence variation, coherence, and common characteristics of LLM-generated writing. Do not rely on any single feature.

    Return ONLY valid JSON in exactly this format:

    {{
        "ai_probability": 0.73,
        "reasoning": "Brief explanation."
    }}

    Rules:
    - ai_probability must be a decimal between 0.0 and 1.0.
    - reasoning should be one short sentence.
    - Do not include markdown.
    - Do not include any extra text.

    Text:
    \"\"\"
    {text}
    \"\"\"
    """

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            temperature=0,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        result = json.loads(response.choices[0].message.content)

        return {
            "signal": "llm_classifier",
            "ai_probability": round(float(result["ai_probability"]), 2),
            "reasoning": result["reasoning"]
        }

    except Exception as e:
        print("Groq error:", e)

        return {
            "signal": "llm_classifier",
            "ai_probability": 0.5,
            "reasoning": "LLM classifier unavailable."
        }

def generate_label(confidence):
    if confidence >= 0.75:
        return (
            "This content was classified as likely AI-generated with high confidence. "
            "This result is based on multiple automated detection signals and may be appealed by the creator."
        )

    if confidence <= 0.25:
        return (
            "This content appears to be human-written with high confidence. "
            "This assessment is based on multiple automated detection signals and is not a guarantee of authorship."
        )

    return (
        "The system could not confidently determine whether this content was "
        "human-written or AI-generated. Readers should treat this label as "
        "additional context rather than a final judgment."
    )

def stylometric_analyzer(text):
    """
    Second detection signal.
    Computes stylometric features and returns an AI-probability score from 0 to 1.
    """

    sentences = re.split(r"[.!?]+", text)
    sentences = [s.strip() for s in sentences if s.strip()]

    words = re.findall(r"\b\w+\b", text.lower())
    word_count = len(words)

    if word_count == 0:
        return {
            "signal": "stylometric_heuristics",
            "ai_probability": 0.5,
            "features": {},
            "reasoning": "No usable words found, so this signal is uncertain.",
        }

    unique_words = len(set(words))
    type_token_ratio = unique_words / word_count

    sentence_lengths = [len(re.findall(r"\b\w+\b", s)) for s in sentences]

    if len(sentence_lengths) > 1:
        avg_sentence_length = sum(sentence_lengths) / len(sentence_lengths)
        sentence_length_variance = sum(
            (length - avg_sentence_length) ** 2 for length in sentence_lengths
        ) / len(sentence_lengths)
    else:
        avg_sentence_length = sentence_lengths[0] if sentence_lengths else word_count
        sentence_length_variance = 0

    punctuation_count = sum(1 for char in text if char in string.punctuation)
    punctuation_density = punctuation_count / max(len(text), 1)

    score = 0.5

    if sentence_length_variance < 10:
        score += 0.10
    elif sentence_length_variance < 25:
        score += 0.05
    else:
        score -= 0.05

    if type_token_ratio < 0.45:
        score += 0.10
    elif type_token_ratio < 0.60:
        score += 0.05
    else:
        score -= 0.05

    if punctuation_density < 0.035:
        score += 0.07
    else:
        score -= 0.03

    score = max(0.0, min(score, 1.0))

    return {
        "signal": "stylometric_heuristics",
        "ai_probability": round(score, 2),
        "features": {
            "word_count": word_count,
            "sentence_count": len(sentences),
            "avg_sentence_length": round(avg_sentence_length, 2),
            "sentence_length_variance": round(sentence_length_variance, 3),
            "type_token_ratio": round(type_token_ratio, 3),
            "punctuation_density": round(punctuation_density, 3),
        },
        "reasoning": (
            "Score is based on sentence length variance, vocabulary diversity, "
            "and punctuation density."
        ),
    }


def calculate_confidence(llm_score, stylometric_score):
    """
    planning.md formula:
    combined_ai_probability = (0.65 * llm_score) + (0.35 * stylometric_score)
    """
    combined_score = (0.65 * llm_score) + (0.35 * stylometric_score)
    return round(combined_score, 2)


def classify_attribution(confidence):
    """
    planning.md thresholds:
    0.00–0.25 = likely_human
    0.26–0.74 = uncertain
    0.75–1.00 = likely_ai
    """
    if confidence <= 0.25:
        return "likely_human"
    if confidence >= 0.75:
        return "likely_ai"
    return "uncertain"


@app.route("/submit", methods=["POST"])
@limiter.limit("5 per minute")
def submit():
    data = request.get_json()

    if not data:
        return jsonify({"error": "Request body must be valid JSON."}), 400

    text = data.get("text")
    creator_id = data.get("creator_id")

    if not text or not isinstance(text, str):
        return jsonify({"error": "Missing or invalid field: text."}), 400

    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id."}), 400

    content_id = str(uuid.uuid4())

    llm_signal = llm_based_classifier(text)
    stylometric_signal = stylometric_analyzer(text)

    llm_score = llm_signal["ai_probability"]
    stylometric_score = stylometric_signal["ai_probability"]

    confidence = calculate_confidence(llm_score, stylometric_score)
    attribution = classify_attribution(confidence)
    label = generate_label(confidence)

    log_event({
        "event_type": "submission",
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "status": "classified",
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "signals": {
            "llm_classifier": llm_signal,
            "stylometric_heuristics": stylometric_signal,
        },
        "status": "classified",
    })

def find_content_by_id(content_id):
    entries = get_log(limit=1000)

    for entry in reversed(entries):
        if (
            entry.get("content_id") == content_id
            and entry.get("event_type") == "submission"
        ):
            return entry

    return None

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()

    if not data:
        return jsonify({"error": "Request body must be valid JSON."}), 400

    content_id = data.get("content_id")
    appeal_reasoning = data.get("creator_reasoning")

    if not content_id:
        return jsonify({"error": "Missing required field: content_id."}), 400

    if not appeal_reasoning or not isinstance(appeal_reasoning, str):
        return jsonify({"error": "Missing or invalid required field: creator_reasoning."}), 400

    original_decision = find_content_by_id(content_id)

    if not original_decision:
        return jsonify({"error": "No submission found for that content_id."}), 404

    appeal_id = str(uuid.uuid4())
    creator_id = original_decision.get("creator_id")

    log_event({
        "event_type": "appeal",
        "appeal_id": appeal_id,
        "content_id": content_id,
        "creator_id": creator_id,
        "appeal_reasoning": appeal_reasoning,
        "original_attribution": original_decision.get("attribution"),
        "original_confidence": original_decision.get("confidence"),
        "original_llm_score": original_decision.get("llm_score"),
        "original_stylometric_score": original_decision.get("stylometric_score"),
        "status": "under_review",
    })

    return jsonify({
        "appeal_id": appeal_id,
        "content_id": content_id,
        "status": "under_review",
        "message": "Appeal submitted for review."
    })

def get_analytics():
    entries = get_log(limit=1000)

    submissions = [e for e in entries if e.get("event_type") == "submission"]
    appeals = [e for e in entries if e.get("event_type") == "appeal"]

    attribution_counts = {
        "likely_ai": 0,
        "likely_human": 0,
        "uncertain": 0,
    }

    for entry in submissions:
        attribution = entry.get("attribution")
        if attribution in attribution_counts:
            attribution_counts[attribution] += 1

    def avg(values):
        values = [v for v in values if isinstance(v, (int, float))]
        return round(sum(values) / len(values), 2) if values else 0

    total_submissions = len(submissions)
    total_appeals = len(appeals)

    return {
        "total_submissions": total_submissions,
        "total_appeals": total_appeals,
        "appeal_rate": round(total_appeals / total_submissions, 2) if total_submissions else 0,
        "attribution_counts": attribution_counts,
        "average_confidence": avg([e.get("confidence") for e in submissions]),
        "average_llm_score": avg([e.get("llm_score") for e in submissions]),
        "average_stylometric_score": avg([e.get("stylometric_score") for e in submissions]),
    }


@app.route("/analytics", methods=["GET"])
def analytics():
    return jsonify(get_analytics())


@app.route("/dashboard")
def dashboard():
    data = get_analytics()

    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Provenance Guard Dashboard</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                max-width: 900px;
                margin: 40px auto;
                background: #f6f8fb;
                color: #222;
            }}

            h1 {{
                color: #2b5cff;
            }}

            .card {{
                background: white;
                padding: 20px;
                margin-bottom: 20px;
                border-radius: 10px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            }}

            ul {{
                padding-left: 20px;
            }}

            .metric {{
                font-size: 24px;
                font-weight: bold;
                color: #2b5cff;
            }}
        </style>
    </head>

    <body>

        <h1>Provenance Guard Analytics Dashboard</h1>

        <div class="card">
            <h2>Summary</h2>

            <p>Total submissions</p>
            <div class="metric">{data["total_submissions"]}</div>

            <p>Total appeals</p>
            <div class="metric">{data["total_appeals"]}</div>

            <p>Appeal rate</p>
            <div class="metric">{data["appeal_rate"]:.2f}</div>
        </div>

        <div class="card">
            <h2>Detection Patterns</h2>

            <ul>
                <li>Likely AI: {data["attribution_counts"]["likely_ai"]}</li>
                <li>Likely Human: {data["attribution_counts"]["likely_human"]}</li>
                <li>Uncertain: {data["attribution_counts"]["uncertain"]}</li>
            </ul>
        </div>

        <div class="card">
            <h2>Average Scores</h2>

            <ul>
                <li>Average confidence: {data["average_confidence"]}</li>
                <li>Average LLM score: {data["average_llm_score"]}</li>
                <li>Average stylometric score: {data["average_stylometric_score"]}</li>
            </ul>
        </div>

    </body>
    </html>
    """

@app.route("/log", methods=["GET"])
def log():
    return jsonify({
        "entries": get_log()
    })

if __name__ == "__main__":
    app.run(debug=True)